version: "3"
services:
  pod_orgs:
    build:
      context: .
    image: pod_orgs
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
